apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: {{ include "demo.ns" . }}
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongo.user }}
  MONGO_INITDB_ROOT_PASSWORD: {{ default (randAlphaNum 32) .Values.secrets.mongo.password | b64enc }}
