apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-servers
  namespace: {{ include "demo.ns" . }}
data:
  servers.json: |
    {
      "Servers": {
        "1": {
          "Name": "postgres",
          "Group": "Servers",
          "Host": "postgres-svc.{{ include "demo.ns" . }}.svc.cluster.local",
          "Port": 5432,
          "MaintenanceDB": "{{ .Values.postgres.db }}",
          "Username": "{{ .Values.postgres.user }}",
          "SSLMode": "prefer",
          "ConnectNow": false
        }
      }
    }
