apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: {{ include "demo.ns" . }}
spec:
  replicas: 1
  selector:
    matchLabels: { app: pgadmin }
  template:
    metadata:
      labels: { app: pgadmin }
    spec:
      containers:
        - name: pgadmin
          image: {{ .Values.pgadmin.image }}
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: pgadmin-secret
          volumeMounts:
            - name: pgadmin-data
              mountPath: /var/lib/pgadmin
            - name: pgadmin-servers
              mountPath: /pgadmin4/servers.json
              subPath: servers.json
      volumes:
        - name: pgadmin-data
          persistentVolumeClaim:
            claimName: pgadmin-pvc
        - name: pgadmin-servers
          configMap:
            name: pgadmin-servers
