{{- if .Values.pgadmin.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pgadmin-ing
  namespace: {{ include "demo.ns" . }}
spec:
  ingressClassName: {{ .Values.pgadmin.ingress.className }}
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pgadmin-svc
                port:
                  number: 80
{{- end }}
