apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
  namespace: {{ include "demo.ns" . }}
type: Opaque
stringData:
  PGADMIN_DEFAULT_EMAIL: {{ .Values.pgadmin.email }}
  PGADMIN_DEFAULT_PASSWORD: {{ default (randAlphaNum 32) .Values.secrets.pgadmin.password | b64enc }}
