apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: {{ include "demo.ns" . }}
spec:
  type: ClusterIP
  selector: { app: postgres }
  ports:
    - port: 5432
      targetPort: 5432
