apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ include "demo.ns" . }}
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.postgres.db }}
  POSTGRES_USER: {{ .Values.postgres.user }}
  POSTGRES_PASSWORD: {{ default (randAlphaNum 32) .Values.secrets.postgres.password | b64enc }}
