apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: {{ include "demo.ns" . }}
type: Opaque
stringData:
  REDIS_PASSWORD: {{ default (randAlphaNum 32) .Values.secrets.redis.password | b64enc }}
